### ISSUE TITLE
doc: Categorize connectors

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-site#166]
Categorizing connectors might make it easier for connectors to be discovered. E.g. 
* AWS
* GCP
* Relational databases
* etc.

**Comment by raulb** [comment]
If we believe this categorization is relevant, I think the work would be done as part of https://github.com/ConduitIO/conduit/issues/1523. 

Before we get into that, I believe we need to ensure that the categorization makes sense. In particular, what would be included in `etc.` so every possible connector has a category that's intuitive.

Maybe, we could have these categorization as **tags**, so those would be used to filter them out on the UI.

E.g.:

```yaml
# connector.yaml
version: 1.0
connector:
  name: postgres
  author: Meroxa, Inc.
  version: v1.0.0
  summary: ...
  tags:
    - relational database
  description: |
    ...
  # ------------------------ GENERATED ------------------------
  ...
```

If we go in that direction, we need to make sure we don't add tags freely, but rather try to use any other previously created ones so the categorization is actually useful.
